name: evm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: lint sol & js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run lint
        working-directory: ./contract
        run: npm run lint

  tests:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run hardhat tests
        working-directory: ./contract
        run: npm run test:hardhat
      - name: Run foundry tests
        working-directory: ./contract
        run: npm run test:forge
